### ISSUE TITLE
gulp-cssnano is breaking attribute-selectors

### ISSUE THREAD

**Issue by joville** [vkemeter/frontend-pipeline-main#25]
While working with this pipeline, I found out that attribute-selectors doesn't work as properly as it should!

The package gulp-cssnano is breaking attribute selectors and this is not seemingly fixed in cssnano, too. The issues are:

1. gulp-cssnano is not maintained anymore and therefore dependency is not updated
2. cssnano is still not working nice with attribut-selectors

Removing the line `.pipe(_minify({ zindex: false }))` in `scss.js` in the frontend gulp-tasks proof-checked my assumption.

We need a workaround for this as soon as possible!

Update:

I would replace gulp-cssnano with [gulp-clean-css](https://www.npmjs.com/package/gulp-clean-css)

**Comment by vkemeter** [comment]
css-nano is already removed in the development branch. will merge it as soon as possible.

**Comment by vkemeter** [comment]
we dont need a workaround or replacement due to node-sass returns already minified css. please take a look into the dev branch for example code.

**Comment by joville** [comment]
Oh well, never mind! Thanks for the hint.
